### ISSUE TITLE
Not posix compliant.

### ISSUE THREAD

**Issue by PaiZuZe** [PaiZuZe/multigrep#1]
In the getfiles function we use the field d_type of the dirent strut, according to http://man7.org/linux/man-pages/man3/readdir.3.html, this field is not a POSIX requirement, so we cannot guarantee that multigrep will work across all Linux devices.

**Comment by GuilhermeVieira** [comment]
It might not work across over all unix devices, but definitely will work on linux ones. Our target are only linux devices, so this is not revelant for our project.
